jobs:
- name: anynines_blog_build_job
  plan:
  - get: anynines_blog_dockerfile
    trigger: true
  - put: anynines_blog_build_image
    params: {build: anynines_blog_dockerfile}
resources:
- name: anynines_blog_dockerfile
  type: git
  source:
   uri: https://github.com/n-trace/anynines_blog.git
- name: anynines_blog_build_image
  type: docker-image
  source:
   repository: ntrace/anynines_blog
   email: ((docker_mail))
   username: ((docker_user))
   password: ((docker_pass))
